<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Are you sure you want to delete this item?' => 'Você deseja realmente excluir este item?',
  'Delete' => 'Excluir',
  'Displaying {start}-{end} of {count} result(s).' => 'Exibindo resultado(s) {start}-{end} de {count}.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'Um dos dois, "name" ou "value" devem ser especificados para CDataColumn.',
  'No results found.' => 'Nenhum resultado encontrado.',
  'Not set' => 'Não definido',
  'Please specify the "attributes" property.' => 'Favor especificar a propriedade "attributes".',
  'Please specify the "data" property.' => 'Favor especificar a propriedade "data".',
  'Sort by: ' => 'Ordenar por: ',
  'The "dataProvider" property cannot be empty.' => 'A propriedade "dataProvider" não pode ser vazia.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'O atributo deve ser especificado no formato "Name:Type:Label", onde "Type" e "Label" são opcionais.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'A coluna deve ser especificada no formato "Name:Type:Label", onde "Type" e "Label" são opcionais.',
  'The property "itemView" cannot be empty.' => 'A propriedade "itemView" não pode ser vazia.',
  'Total {count} result(s).' => 'Total de resultado(s): {count}.',
  'Update' => 'Atualizar',
  'View' => 'Exibir',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} deve especificar valores para as propriedades "model" e "attribute" ou "name".',
);
