<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '$_SERVER does not have {vars}.' => 'Переменная $_SERVER не содержит {vars}.',
  '$_SERVER variable' => 'Переменная $_SERVER.',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => 'Переменная $_SERVER["SCRIPT_FILENAME"] должна соответствовать пути к файлу входного скрипта.',
  'APC extension' => 'Расширение APC',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Все <a href="http://www.yiiframework.com/doc/api/#system.db">DB-классы</a>',
  'DOM extension' => 'Библиотека DOM',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Должна существовать хотя бы одна из серверных переменных: $_SERVER["REQUEST_URI"] или $_SERVER["QUERY_STRING"].',
  'GD extension' => 'Библиотека GD',
  'Mcrypt extension' => 'Библиотека Mcrypt',
  'Memcache extension' => 'Библиотека Memcache',
  'PCRE extension' => 'Библиотека PCRE',
  'PDO MySQL extension' => 'Библиотека PDO MySQL',
  'PDO PostgreSQL extension' => 'Библиотека PDO PostgreSQL',
  'PDO SQLite extension' => 'Библиотека PDO SQLite',
  'PDO extension' => 'Библиотека PDO',
  'PHP 5.1.0 or higher is required.' => 'Необходима версия РНР 5.1.0 и выше.',
  'PHP version' => 'Версия РНР',
  'Reflection extension' => 'Библиотека',
  'SOAP extension' => 'Библиотека SOAP',
  'SPL extension' => 'Библиотека SPL',
  'This is required by encrypt and decrypt methods.' => 'Требуется для работы методов шифрации/дешифрации.',
  'This is required if you are using MySQL database.' => 'Требуется для работы с БД MySQL.',
  'This is required if you are using PostgreSQL database.' => 'Требуется для работы с БД PostgreSQL.',
  'This is required if you are using SQLite database.' => 'Требуется для работы с БД SQLite.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Не получилось получить информацию об адресе URL. Пожалуйста, проверьте переменные $_SERVER["PATH_INFO"] (или $_SERVER["PHP_SELF"] и $_SERVER["SCRIPT_NAME"]) на наличие корректных значений.',
);
