<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Are you sure you want to delete this item?' => 'Czy jesteœ pewien, ¿e chcesz usun¹æ tê pozycjê?',
  'Delete' => 'usuñ',
  'Displaying {start}-{end} of {count} result(s).' => 'Wyœwietlanie wyników: {start}-{end} z {count} result(s).',
  'Either "name" or "value" must be specified for CDataColumn.' => 'Zarówno nazwa "name" oraz wartoœæ "value" musz¹ byæ okreœlone dla CDataColumn.',
  'Home' => 'Start',
  'No results found.' => 'Brak trafieñ.',
  'Not set' => 'Nie ustawiono',
  'Please specify the "attributes" property.' => 'Okreœl w³aœciwoœæ "attributes".',
  'Please specify the "data" property.' => 'Okreœl w³aœciwoœæ "data".',
  'Sort by: ' => 'Sortowanie:',
  'The "dataProvider" property cannot be empty.' => 'W³aœciwoœæ "dataProvider" nie mo¿e byæ pusta.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Atrybut powinien byæ zdefiniowany u¿ywaj¹c formatu "Name:Type:Label", gdzie typ "Type" oraz etykieta "Label" s¹ opcjonalne.',
  'The button type "{type}" is not supported.' => 'Brak wsparcia dla typu przycisku "{type}".',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Kolumna musi byæ zdefiniowana u¿ywaj¹c formatu "Name:Type:Label", gdzie type "Type" oraz etykieta "Label" s¹ opcjonalne.',
  'The property "itemView" cannot be empty.' => 'W³aœciwoœæ "itemView" nie mo¿e byæ pusta.',
  'Total {count} result(s).' => 'Razem {count}.',
  'Update' => 'zmieñ',
  'View' => 'podgl¹d',
  '{class} must specify "model" and "attribute" or "name" property values.' => 'Klasa {class} musi definiowaæ w³aœciwoœci modelu "model" oraz atrybutu "attribute" lub nazwy "name".',
);
